version: 0.4.6

namespace: games
project: games

services:
  - name: web
    image: ghcr.io/markmorcos/games-web
    context: web
    port: 80
    ingress:
      host: games.morcos.tech
      path: /?(.*)
      pathType: ImplementationSpecific
  # - name: api
  #   image: ghcr.io/markmorcos/games-server
  #   context: server
  #   port: 3000
  #   env:
  #     - name: MONGO_URI
  #       valueFrom:
  #         secretKeyRef:
  #           name: memory-database-secret
  #           key: MONGO_URI
  #   ingress:
  #     host: games.morcos.tech
  #     path: /api/?(.*)
  #     pathType: ImplementationSpecific
  # - name: socket
  #   context: socket
  #   image: ghcr.io/markmorcos/games-socket
  #   port: 8080
  #   ingress:
  #     host: games.morcos.tech
  #     path: /socket/?(.*)
  #     pathType: ImplementationSpecific
